server:
  port: 1515
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
            - email
            - profile

          naver:
            client-id:
            client-secret:
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:1515/login/oauth2/code/naver

        provider:
          naver:
            #이 주소로 등록하면 네이버 로그인 창이 뜬다.
            #loginForm에서 /oauth2/authorization/naver 이 링크로 요청 시
            #아래 설정한 주소로 요청이 된다.
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            #토큰을 받으려면 아래의 주소를 사용해야한다.
            token-uri: https://nid.naver.com/oauth2.0/token
            #프로필 주소를 받으려면 아래의 주소를 사용해야한다.
            user-info-uri: https://openapi.naver.com/v1/nid/me
            # 회원 정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해준다.
            # 즉 프로필을 호출하여 응답을 받으면 그 응답받은 모든 정보들이 response라는 키값으로 저장됨
            user-name-attribute: response




